name: machine_test
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  badges: ^3.1.1
  cupertino_icons: ^1.0.2
  flashy_tab_bar2: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/sandwich_icon.svg
    - assets/images/default_avatar.png
